reworked terminology section
AnonCreds-WG/anoncreds-spec pull request #66
Opened 2022-08-01 13:25 UTC by ArPhil

Signed-off-by: Artur Philipp <artur.philipp@posteo.de>

2022-08-01 13:27 UTC, ArPhil commented
Worked a bit on the terminology part:

- Added terminology for a) Credential Request b) Credential Offer c) Verifiable Data Registry
- Sorted terminology in lexigraphical order
- Remaned "Table of contets" to "Summary of contents", since we already have a ToC on the left pane in the doc. I`d rather like to have some summarizing text of the various sections of the spec here.
- Elaborated further on some parts like CRED_DEF.

2022-08-02 23:42 UTC, swcurran approved these changes
This looks good.  Note that:

- matching is case-insensitive, so it is OK to put the definition in a consistent format
- the definition can be a comma-separated list with synonyms following the main definition. The synonyms are NOT listed, so you can have `Claim, claims` to get the matches on `claims` as a reference.

I'm happy. to have this merged now, as we will do more passes on this. Or @ArPhil , you might want to adjust the way each entry is named and add some synonyms.

We don't want this PR open long as we have others that need it merged.

2022-08-03 06:54 UTC, ArPhil commented
@swcurran , thanks for the hint with the synonyms. I hope I catched all of the inconsistencies! :-)

Also added `Non-Revocation Proof (NRP)` to the terminology section. I believe that we can merge it now.

2022-08-03 22:41 UTC, swcurran requested changes
I found a couple of typos, so requested a change and added another random comment that you can change or ignore as you think best.

2022-08-03 22:41 UTC, swcurran commented on spec/terminology.md
> +[[def: CRED_DEF, CDRED_DEFs]]
Typo on this line -- CDRED.  Also, what about adding "CLAIM_DEF" as a synonym?

2022-08-03 22:41 UTC, swcurran commented on spec/terminology.md
> +:::todo
Hmmm...maybe we make CRED_DEF_PRIVATE a symonym as well, and include it's definition here?  Or do we need a separate entry?

2022-08-03 22:41 UTC, swcurran commented on spec/terminology.md
> +~ AnonCreds are bound to the [[ref: holder]] with a non-correlatable secret only known to the [[ref: holder]] itself called a link secret*. Instead of a persistent identifier, the link secret as a bl
Ooppss...another typo -- calim.

2022-08-04 08:25 UTC, ArPhil commented on spec/terminology.md
> +[[def: CRED_DEF, CDRED_DEFs]]
Fixed Type. Added CLAIM_DEF as a synonym.

2022-08-04 08:31 UTC, ArPhil commented on spec/terminology.md
> +:::todo
Good point! At same sections in the spec I had the feeling, that the difference might not always be entirely clear to the reader. I added not all variants of synonyms to the CRED_DEF: 

`[[def: CRED_DEF, CRED_DEFs, CLAIM_DEF, CLAIM_DEFs, CRED_DEF_PRIVATE, CRED_DEF_PUBLIC]]`

I believe, that we should have one `CRED_DEF` in the terminology section, where we elaborete within that definition the difference between the public and private part of it. To me a `CRED_DEF` is one single thing, which is just divided into two parts, that are stored in different places (ledger and wallet). I would like to emphasize the cohesiveness by just providing one definition in the terminology section. 

But of course, we can also discuss this if you or others feel different about it.

2022-08-04 08:33 UTC, ArPhil commented on spec/terminology.md
> +~ AnonCreds are bound to the [[ref: holder]] with a non-correlatable secret only known to the [[ref: holder]] itself called a link secret*. Instead of a persistent identifier, the link secret as a bl
Sorry for that... but thanks for the good eye! :-)

2022-08-04 09:27 UTC, ArPhil commented on spec/terminology.md
> +:::todo
Could not resist and reworked the CRED_DEF part. Please tell me what you think about it.

2022-08-04 13:52 UTC, swcurran approved these changes
LGTM

2022-08-04 13:52 UTC, merged

2022-08-04 13:52 UTC, swcurran commented
Good stuff!