Security Considerations
AnonCreds-WG/anoncreds-spec pull request #68
Opened 2022-08-01 14:23 UTC by hkny

Signed-off-by: Hakan Yildiz <c.hakan.yildiz@gmail.com>

2022-08-08 14:12 UTC, ArPhil commented on spec/security_considerations.md
> +### Verifiable Data Registry
As discussed in the AnonCreds Specification meeting on 08.08.2022:

Would be nice to have some kind of AnonCreds Requirements checklist which can be used in order to verify, that the underlaying VDR is "compatible" / "suitable" for AnonCreds 1.0.

2022-08-08 14:14 UTC, hkny commented on spec/security_considerations.md
> +### Envelope
Mention that there is a necessity to encrypt the credential in an encrypted way. Sufficiently encrypted but not necessarily mention a specific method

2022-08-08 14:15 UTC, hkny commented on spec/security_considerations.md
> +### Transport
same as envelope

2022-08-08 14:17 UTC, hkny commented on spec/security_considerations.md
> +
the signature algorithms might evolve but we must keep privacy-preserving features such as selective disclosure non-correlatability etc.

2022-08-08 14:29 UTC, hkny commented on spec/security_considerations.md
> +#### Revocation / Accumulators
correlation in case of the revocation registries are too small.

2022-08-08 17:16 UTC, swcurran commented on spec/security_considerations.md
> +### Verifiable Data Registry
Your phrasing triggered for me that this is needed in the AnonCreds Objects Method section -- what support is needed in a VDR in order for it to be used for AnonCreds 1.0?  Notably -- the ability to store AnonCreds objects, which are basically resources.

2022-10-21 17:13 UTC, swcurran commented on spec/security_considerations.md
> +It is recommended to follow the best practices of decentralized key management system designs and architectures. The Hyperledger Indy implementation of AnonCreds are built on the following [DKMS Desi
Suggest changing: "The Hyperledger Indy implementation of AnonCreds are built on..."

To: "For example, an option for publishing AnonCreds objects is Hyperledger Indy, which is built on..."

2022-10-21 17:15 UTC, swcurran commented on spec/security_considerations.md
> +AnonCreds should be packed in a message envelope that can fulfill properties such as authenticity, integrity, confidentiality, and non-repudiation of the message. A message can have these properties
Should we say that DIDComm is a good option for this?

2022-10-21 17:17 UTC, swcurran requested changes
A couple of tweaks proposed, with the one about Hyperledger Indy being "an example" is the one that is the requested change.

2022-10-24 09:56 UTC, hkny commented on spec/security_considerations.md
> +AnonCreds should be packed in a message envelope that can fulfill properties such as authenticity, integrity, confidentiality, and non-repudiation of the message. A message can have these properties
For example, Hyperledger Indy utilizes DIDComm v1 as message envelope for exchanging AnonCreds between [[ref: issuer]]s, [[ref: holder]]s, and [[ref: verifier]]s.

2022-10-24 11:23 UTC, ArPhil commented
I believe the current state is a great initial starting point for security considerations. I wonder, should we additionally consider the different perspectives of the roles (VDR, issuer, verifier, holder) on this topic? E.g. :

A holder requires:
- to protect the link secret
- to have options to authenticate other entities (especially the verifier) when sharing data
- ...

A Issuer requires:
- to protect the signing keys of credentials
- make sure, that the holder he wants to issue a credential to, is authentic
- ...

I checked the W3C DID Core and VC Data Model specs. Looks to me, that even there this separation of roles / concerns regarding security is not differentiated too much. But I believe it could help.

2022-10-24 14:18 UTC, swcurran approved these changes

2022-10-24 14:19 UTC, merged